export const CREATE_GROUP = 'CREATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const MERGE_USERGROUP = 'MERGE_USERGROUP';
export const UNMERGE_USERGROUP = 'UNMERGE_USERGROUP';